### ISSUE TITLE
Issue with News() import into pandas dataframe

### ISSUE THREAD

**Issue by t-aha** [oscar0812/pyfinviz#6]
File ".../pyfinviz/news.py", line 28, in __init__
    self.news_df = News.__table_to_df__(main_tables[0])
  File ".../pyfinviz/news.py", line 16, in __table_to_df__
    info.append({'Time': tds[1].text, 'Headline': td_a.text, 'URL': td_a['href']})
IndexError: list index out of range

**Comment by t-aha** [comment]
``

**Comment by KamranAbbaszadeIbrahim** [comment]
Hi, I also faced with current issue.

**Comment by oscar0812** [comment]
Hello! This issue should be fixed in the [latest commit ](https://github.com/oscar0812/pyfinviz/commit/59c6618ff56ab015c45c3b6be588bf5540d8833f#diff-22cea4e42c7fd20057d91f0db0abc52344fbc965d48c1e44e8a4d835be195bb6). I will close this issue after confirmation 😄

**Comment by KamranAbbaszadeIbrahim** [comment]
@oscar0812 
when I try to install pyfinviz using 
```
pip install --upgrade pyfinviz
```
it has been installed successfully, the bug is still there.
Have you published the release? or could you please specify the version which contains fixed version?

**Comment by KamranAbbaszadeIbrahim** [comment]
@oscar0812 
Any updates?

**Comment by t-aha** [comment]
I updated pyfinviz and am still experiencing this error

**Comment by oscar0812** [comment]
Thank you for your patience. Please update the package now and check: [https://pypi.org/project/pyfinviz/0.8/](https://pypi.org/project/pyfinviz/0.8/).

**Comment by KamranAbbaszadeIbrahim** [comment]
Resolved. Now it is working properly.
